name: TeamPacketModifier
version: '${version}'
main: awa.xunfeng.TPM.TeamPacketModifier
api-version: '1.20'
depend: [ProtocolLib]

commands:
  TPM:
    aliases:
      - "tpm"# 别名，方便玩家使用
    usage: "/tpm <reload/enable/disable/status>" # 用法
    description: "Reload TPM features." # 描述
    permission: "minecraft.command.op" # 需要的权限
    permission-message: "Only OP can do that!" # 无权限返回的消息